Traceback (most recent call last):
  File "train.py", line 285, in <module>
    train(opt)
  File "train.py", line 233, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/local_host/docker_containers/paper/grnet/eval_utils.py", line 120, in eval_split
    seq = model(fc_feats, att_feats, att_masks, opt=eval_kwargs, mode='sample')[0].data
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/local_host/docker_containers/paper/grnet/models/CaptionModel.py", line 34, in forward
    return getattr(self, '_'+mode)(*args, **kwargs)
  File "/local_host/docker_containers/paper/grnet/models/AttModel.py", line 197, in _sample
    logprobs, state = self.get_logprobs_state(it, p_fc_feats, p_att_feats, pp_att_feats, p_att_masks, state)
  File "/local_host/docker_containers/paper/grnet/models/AttModel.py", line 137, in get_logprobs_state
    output, state = self.core(xt, fc_feats, att_feats, p_att_feats, state, att_masks)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() takes from 5 to 6 positional arguments but 7 were given
Terminating BlobFetcher
